"""Runtime constants sourced from EBTA-DOC-1.0."""

import os  # PREUVE VOLONTAIRE lot 3 : import inutilise, Ruff F401, sera reverte

PROTOCOL_VERSION = "EBTA-DOC-1.0"
ENGINE_VERSION = "EBTA-ENGINE-0.1.0"
SCHEMA_VERSION = "2.0.0"

# Source: Protocole/REGISTRE DES DECISIONS NORMATIVES EBTA.md, taxonomie globale.
VALIDATION_STATUSES = {"PASS", "NOT_VALIDATED", "REJECTED_ECONOMIC", "FAIL", "INCONCLUSIVE"}
LOCAL_FOLD_STATUSES = {"NO_MODEL", "STOP_PROCESS"}
TECHNICAL_STATUSES = {"INVALID_TECHNICAL"}
MONITORING_STATUSES = {"WATCH", "PASS", "FAIL", "INCONCLUSIVE"}
PACKAGE_STAGES = {"PRE_OOS_SEALED", "VALIDATION_READY", "DEPLOYMENT_CERTIFIED", "LIFECYCLE_ARCHIVED"}

ALL_DECISION_STATUSES = (
    VALIDATION_STATUSES | LOCAL_FOLD_STATUSES | TECHNICAL_STATUSES | MONITORING_STATUSES | PACKAGE_STAGES
)
