"""Machine-readable EBTA G-BIAS risk registry.

Source: Protocole/BIAS_RISK_REGISTER.md and SOP 13.
Type: CONTRACT_ENCODING.
"""

from __future__ import annotations

from copy import deepcopy
from typing import Any


BIAS_RISKS: tuple[dict[str, Any], ...] = (
    {
        "schema_version": "1.0.0",
        "bias_id": "BIAS-001",
        "name": "P-hacking",
        "description": "Repeated or opportunistic testing until a favorable result appears.",
        "phase": ["TRAIN", "TEST", "PRE_OOS"],
        "default_severity": "LEVEL_2",
        "detectors": ["registry_completeness_checker", "metric_lock_checker"],
        "controlled_artifacts": ["registry.jsonl", "config.json", "reports/wrc.json"],
        "impacted_gates": ["G-BIAS", "G6", "G8"],
        "corrective_procedure": "Block OOS and replay the complete preregistered family when material.",
        "sop_reference": "SOP 13",
    },
    {
        "schema_version": "1.0.0",
        "bias_id": "BIAS-002",
        "name": "Data snooping",
        "description": "Using observed data behavior to reshape the tested family or decision rule.",
        "phase": ["TRAIN", "TEST", "PRE_OOS"],
        "default_severity": "LEVEL_2",
        "detectors": ["registry_completeness_checker", "candidate_family_checker"],
        "controlled_artifacts": ["registry.jsonl", "reports/candidate_matrix.json"],
        "impacted_gates": ["G-BIAS", "G6", "G8"],
        "corrective_procedure": "Reconstruct the family and rerun WRC/MCP before any OOS opening.",
        "sop_reference": "SOP 13",
    },
    {
        "schema_version": "1.0.0",
        "bias_id": "BIAS-003",
        "name": "HARKing",
        "description": "Presenting a hypothesis discovered after results as if it were preregistered.",
        "phase": ["TEST", "PRE_OOS", "POST_OOS"],
        "default_severity": "LEVEL_2",
        "detectors": ["preregistration_checker"],
        "controlled_artifacts": ["config.json", "manifests/reproducibility_manifest.json"],
        "impacted_gates": ["G-BIAS", "G0", "G11"],
        "corrective_procedure": "Demote the result to exploratory unless a clean confirmation segment exists.",
        "sop_reference": "SOP 13",
    },
    {
        "schema_version": "1.0.0",
        "bias_id": "BIAS-004",
        "name": "Candidate cherry-picking",
        "description": "Removing or hiding candidates that influenced selection or inference.",
        "phase": ["TEST", "PRE_OOS"],
        "default_severity": "LEVEL_2",
        "detectors": ["candidate_family_checker", "registry_completeness_checker"],
        "controlled_artifacts": ["registry.jsonl", "reports/candidate_matrix.json", "reports/wrc.json"],
        "impacted_gates": ["G-BIAS", "G6", "G8"],
        "corrective_procedure": "Restore the complete family and rerun WRC/MCP.",
        "sop_reference": "SOP 13",
    },
    {
        "schema_version": "1.0.0",
        "bias_id": "BIAS-005",
        "name": "Asset cherry-picking",
        "description": "Removing losing assets from a selectable strategy x asset universe.",
        "phase": ["TEST", "PRE_OOS"],
        "default_severity": "LEVEL_2",
        "detectors": ["candidate_family_checker"],
        "controlled_artifacts": ["config.json", "reports/search_space.json", "reports/candidate_matrix.json"],
        "impacted_gates": ["G-BIAS", "G6", "G8"],
        "corrective_procedure": "Restore all preregistered assets and replay family-level evidence.",
        "sop_reference": "SOP 13",
    },
    {
        "schema_version": "1.0.0",
        "bias_id": "BIAS-006",
        "name": "Suppression of losing candidates",
        "description": "Deleting failed, interrupted, or losing runs from the evidence trail.",
        "phase": ["TRAIN", "TEST", "PRE_OOS"],
        "default_severity": "LEVEL_2",
        "detectors": ["registry_completeness_checker"],
        "controlled_artifacts": ["registry.jsonl"],
        "impacted_gates": ["G-BIAS", "G3", "G8"],
        "corrective_procedure": "Restore append-only evidence or mark the family inconclusive.",
        "sop_reference": "SOP 13",
    },
    {
        "schema_version": "1.0.0",
        "bias_id": "BIAS-007",
        "name": "Metric shopping",
        "description": "Changing primary or decision metrics after observing outcomes.",
        "phase": ["TEST", "PRE_OOS", "POST_OOS"],
        "default_severity": "LEVEL_2",
        "detectors": ["metric_lock_checker"],
        "controlled_artifacts": ["config.json", "reports/oos.json", "reports/economic.json"],
        "impacted_gates": ["G-BIAS", "G5", "G11"],
        "corrective_procedure": "Fail confirmatory interpretation unless the original metric remains decisive.",
        "sop_reference": "SOP 13",
    },
    {
        "schema_version": "1.0.0",
        "bias_id": "BIAS-008",
        "name": "Benchmark shopping",
        "description": "Changing benchmark or detrending basis after observing results.",
        "phase": ["TEST", "PRE_OOS", "POST_OOS"],
        "default_severity": "LEVEL_2",
        "detectors": ["metric_lock_checker"],
        "controlled_artifacts": ["config.json", "reports/detrending.json"],
        "impacted_gates": ["G-BIAS", "G5", "G11"],
        "corrective_procedure": "Restore preregistered benchmark or classify the result as exploratory.",
        "sop_reference": "SOP 13",
    },
    {
        "schema_version": "1.0.0",
        "bias_id": "BIAS-009",
        "name": "Hurdle shopping",
        "description": "Changing economic or statistical hurdles after observing results.",
        "phase": ["TEST", "PRE_OOS", "POST_OOS"],
        "default_severity": "LEVEL_2",
        "detectors": ["metric_lock_checker"],
        "controlled_artifacts": ["config.json", "reports/gates.json", "reports/economic.json"],
        "impacted_gates": ["G-BIAS", "G12"],
        "corrective_procedure": "Use the preregistered hurdle for verdicts; otherwise fail or mark inconclusive.",
        "sop_reference": "SOP 13",
    },
    {
        "schema_version": "1.0.0",
        "bias_id": "BIAS-010",
        "name": "Robustness shopping",
        "description": "Selecting favorable robustness tests or suppressing unfavorable ones.",
        "phase": ["PRE_OOS", "POST_OOS"],
        "default_severity": "LEVEL_2",
        "detectors": ["robustness_gate_checker"],
        "controlled_artifacts": ["reports/robustness.json"],
        "impacted_gates": ["G-BIAS", "G7", "G8"],
        "corrective_procedure": "Restore the complete preregistered robustness matrix.",
        "sop_reference": "SOP 13",
    },
    {
        "schema_version": "1.0.0",
        "bias_id": "BIAS-011",
        "name": "Repair stress test",
        "description": "Adding or reframing stress tests after observing failure to save a strategy.",
        "phase": ["PRE_OOS", "POST_OOS"],
        "default_severity": "LEVEL_2",
        "detectors": ["robustness_gate_checker"],
        "controlled_artifacts": ["reports/robustness.json"],
        "impacted_gates": ["G-BIAS", "G7", "G11"],
        "corrective_procedure": "Treat post-result additions as diagnostic only, never confirmatory.",
        "sop_reference": "SOP 13",
    },
    {
        "schema_version": "1.0.0",
        "bias_id": "BIAS-012",
        "name": "Post-hoc outlier exclusion",
        "description": "Excluding periods, trades, costs, or observations after seeing results.",
        "phase": ["TEST", "PRE_OOS", "POST_OOS"],
        "default_severity": "LEVEL_2",
        "detectors": ["robustness_gate_checker", "metric_lock_checker"],
        "controlled_artifacts": ["config.json", "reports/execution.json", "reports/robustness.json"],
        "impacted_gates": ["G-BIAS", "G7", "G11"],
        "corrective_procedure": "Reinstate excluded observations or mark the analysis exploratory.",
        "sop_reference": "SOP 13",
    },
    {
        "schema_version": "1.0.0",
        "bias_id": "BIAS-013",
        "name": "Post-hoc regime hypothesis",
        "description": "Explaining failure by a newly invented regime definition without preregistration.",
        "phase": ["POST_OOS"],
        "default_severity": "LEVEL_3",
        "detectors": ["preregistration_checker"],
        "controlled_artifacts": ["config.json", "reports/oos.json"],
        "impacted_gates": ["G-BIAS", "G11"],
        "corrective_procedure": "Record as exploratory post-mortem and require a new clean confirmation.",
        "sop_reference": "SOP 13",
    },
    {
        "schema_version": "1.0.0",
        "bias_id": "BIAS-014",
        "name": "OOS peeking",
        "description": "Consulting OOS outputs before authorized opening.",
        "phase": ["OOS", "POST_OOS"],
        "default_severity": "LEVEL_4",
        "detectors": ["oos_access_guard"],
        "controlled_artifacts": ["oos_access_log.jsonl"],
        "impacted_gates": ["G-BIAS", "G8", "G11"],
        "corrective_procedure": "Mark the impacted OOS segment BURNED for influenced descendants.",
        "sop_reference": "SOP 13",
    },
    {
        "schema_version": "1.0.0",
        "bias_id": "BIAS-015",
        "name": "OOS repair",
        "description": "Changing code, rules, costs, or narrative after observing OOS.",
        "phase": ["OOS", "POST_OOS"],
        "default_severity": "LEVEL_4",
        "detectors": ["oos_access_guard", "metric_lock_checker"],
        "controlled_artifacts": ["oos_access_log.jsonl", "manifests/reproducibility_manifest.json"],
        "impacted_gates": ["G-BIAS", "G11"],
        "corrective_procedure": "Burn the contaminated OOS evidence and require future independent confirmation.",
        "sop_reference": "SOP 13",
    },
    {
        "schema_version": "1.0.0",
        "bias_id": "BIAS-016",
        "name": "Opportunistic bug handling",
        "description": "Treating bugs differently depending on whether the correction helps the result.",
        "phase": ["TEST", "PRE_OOS", "POST_OOS"],
        "default_severity": "LEVEL_2",
        "detectors": ["preregistration_checker", "incident_logger"],
        "controlled_artifacts": ["manifests/reproducibility_manifest.json", "reports/reproduction.json"],
        "impacted_gates": ["G-BIAS", "G11"],
        "corrective_procedure": "Apply technical correction rules consistently and document incident impact.",
        "sop_reference": "SOP 13",
    },
    {
        "schema_version": "1.0.0",
        "bias_id": "BIAS-017",
        "name": "Disguised retest",
        "description": "Reusing contaminated OOS evidence as if it were a fresh confirmation.",
        "phase": ["POST_OOS"],
        "default_severity": "LEVEL_4",
        "detectors": ["oos_access_guard", "incident_logger"],
        "controlled_artifacts": ["oos_access_log.jsonl", "reports/reproduction.json"],
        "impacted_gates": ["G-BIAS", "G11"],
        "corrective_procedure": "Reject confirmatory status and require a new independent OOS segment.",
        "sop_reference": "SOP 13",
    },
    {
        "schema_version": "1.0.0",
        "bias_id": "BIAS-018",
        "name": "Post-failure narrative",
        "description": "Recasting a failed or inconclusive result as confirmatory through narrative.",
        "phase": ["POST_OOS", "LIVE"],
        "default_severity": "LEVEL_3",
        "detectors": ["preregistration_checker", "incident_logger"],
        "controlled_artifacts": ["reports/oos.json", "reports/reproduction.json"],
        "impacted_gates": ["G-BIAS", "G11"],
        "corrective_procedure": "Keep the failed verdict and separate exploratory explanation from validation.",
        "sop_reference": "SOP 13",
    },
    {
        "schema_version": "1.0.0",
        "bias_id": "BIAS-019",
        "name": "Opportunistic cost selection",
        "description": "Changing cost, slippage, capacity, or execution assumptions after results.",
        "phase": ["TEST", "PRE_OOS", "POST_OOS"],
        "default_severity": "LEVEL_2",
        "detectors": ["metric_lock_checker"],
        "controlled_artifacts": ["config.json", "reports/execution.json", "reports/economic.json"],
        "impacted_gates": ["G-BIAS", "G12"],
        "corrective_procedure": "Restore preregistered costs or fail the economic interpretation.",
        "sop_reference": "SOP 13",
    },
    {
        "schema_version": "1.0.0",
        "bias_id": "BIAS-020",
        "name": "AI-agent contamination",
        "description": "An assistant or agent uses unavailable evidence or suggests repair after protected exposure.",
        "phase": ["PRE_OOS", "OOS", "POST_OOS"],
        "default_severity": "LEVEL_4",
        "detectors": ["oos_access_guard", "incident_logger"],
        "controlled_artifacts": ["oos_access_log.jsonl", "reports/reproduction.json"],
        "impacted_gates": ["G-BIAS", "G8", "G11"],
        "corrective_procedure": "Declare incident, isolate contaminated outputs, and burn impacted OOS if exposure occurred.",
        "sop_reference": "SOP 13",
    },
)


def list_bias_risks() -> list[dict[str, Any]]:
    """Return a copy of the EBTA-DOC-1.1 bias risk registry."""
    return [deepcopy(entry) for entry in BIAS_RISKS]


def get_bias_risk(bias_id: str) -> dict[str, Any]:
    """Return one bias risk by id or raise KeyError."""
    for entry in BIAS_RISKS:
        if entry["bias_id"] == bias_id:
            return deepcopy(entry)
    raise KeyError(f"Unknown EBTA bias id: {bias_id}")
